### ISSUE TITLE
Unregister on ethical metrics stopped

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DAppNodePackage-ethical-metrics#15]
Implement a SIGKILL handler in the ethical metrics package so that whenever the package is stopped, the dappnode will be removed from the list of dapponodes monitored. This is feasible as the package will automatically try to register itself whenever it is started again.

We could open a specific endpoint like `/unregister` to which the users could send POST requests including their node onion instance to remove it from the monitor.

Also, we should remove the DELETE by email, as we should not depend on email as the only contact way, because other means could be included in the future.

Moreover, we should take into account that we should implement some mechanism for preventing spam, like creating different endpoints depending on the instance that is allowed to unregister from the monitoring service

**Comment by pablomendezroyo** [comment]
Implemented
