### ISSUE TITLE
Implements authentication (client side)

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DAppNodePackage-ethical-metrics#24]
To include authentication in the process we will need to perform the following tasks in the Ethical Metrics package:

1. Proxy will return "Awaiting email confirmation", so we should be sure the user is shown a proper log for this
2. Ethical metrics service should expose an endpoint `/confirm` in an API (preferably written in Go to make it simpler). It could also be exposed in its own service
3. The previous endpoint will be called when clicking in a link included in the welcome email that will look like `http://ethical-metrics.dappnode/confirm?authToken=<TOKEN>
4. The endpoint should redirect the request through the TOR hidden service so that the proxy can set `confirmed=TRUE` for this target

**Comment by dappnodedev** [comment]
Overridden by https://github.com/dappnode/monitor-proxy/issues/67
