### ISSUE TITLE
Consider joining ethical metrics + exporter + DMS packages

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-ethical-metrics#38]
Consider joining ethical metrics + exporter + DMS packages. It might be possible to join concurrently multiple prom and grafana instances

**Comment by pablomendezroyo** [comment]
Research how much would consume all the packages @Marketen 👀

**Comment by dsimog01** [comment]
Also, we need to add a specific warning for "onMajorUpdate", explaining what the user needs to do before installing

**Comment by pablomendezroyo** [comment]
We need to add `backup` to the ethical metrics pkg. In the major update, we should warn about doing the backup if they do not want to register again

**Comment by pablomendezroyo** [comment]
@Marketen isnt already designed like that?

**Comment by Marketen** [comment]
@pablomendezroyo Right now I only see DMS in ethical metrics dependencies. Does dappmanager install DMS dependencies (node exporter) when installing DMS as a dependency itself? 

https://github.com/dappnode/DAppNodePackage-ethical-metrics/blob/c990a3c7e902a5ee5724984d8a768d3947144693/dappnode_package.json#L18

**Comment by pablomendezroyo** [comment]
@Marketen yes, that's how it works

**Comment by pablomendezroyo** [comment]
will not be joined for simplification
