### ISSUE TITLE
Move register daemon logic?

### ISSUE THREAD

**Issue by Marketen** [dappnode/DAppNodePackage-ethical-metrics#50]
Right now, tor-hidden-service tries to register the user through this [daemon](https://github.com/dappnode/DAppNodePackage-ethical-metrics/blob/main/tor-hidden-service/registerOnion.sh).

Since we are implementing a simple service with a UI to register/unregister a instance manually, it makes more sense to migrate this daemon to the same service, since it is also related to instance registation.

**Comment by pablomendezroyo** [comment]
Removed and moved to the dappmanager backend
