### ISSUE TITLE
Delete signal catching from tor-hidden-service

### ISSUE THREAD

**Issue by Marketen** [dappnode/DAppNodePackage-ethical-metrics#51]
Whatever happens, if tor-hidden-service container stops running, we should not unregister automatically since it may make some users unregister when they dont want to and not get notifications when their dappnode is down. 

From now on, if tor-hidden-service container stops gracefully or not, nothing will be sent to monitor proxy server, so user will not  unregister and get notification alerts.

**Comment by dsimog01** [comment]
Duplicate https://github.com/dappnode/DAppNodePackage-ethical-metrics/issues/44
